ALTER TABLE office ALTER COLUMN name SET NOT NULL;

ALTER TABLE alert_type ALTER COLUMN display_name SET NOT NULL;

ALTER TABLE party ALTER COLUMN name SET NOT NULL;

ALTER TABLE party ALTER COLUMN initial SET NOT NULL;

ALTER TABLE state ALTER COLUMN name SET NOT NULL;

ALTER TABLE tag ALTER COLUMN name SET NOT NULL;

ALTER TABLE tag ALTER COLUMN type SET NOT NULL;

ALTER TABLE vote ALTER COLUMN name SET NOT NULL;
