<?php

DEFINE("RABBITMQ_HOST", "localhost");
DEFINE("RABBITMQ_PORT", 5672);
DEFINE("RABBITMQ_VHOST", "/");
DEFINE("RABBITMQ_LOGIN", "guest");
DEFINE("RABBITMQ_PASSWORD", "guest");


DEFINE("MONGODB_HOST", "mongodb://localhost:27017");
DEFINE("MONGODB_NAME", "mobile_advocacy_platform");
DEFINE("MONGODB_USERNAME", "admin");
DEFINE("MONGODB_PASSWORD", "admin");
DEFINE("MONGODB_CONNECT_TIMEOUT", 5000);
DEFINE("MONGODB_COLLECTION_NAME", "mobile_user"); // table name
